name: Python CI with Jupyter & Streamlit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  # Allows manual triggering from the GitHub Actions tab
  workflow_dispatch:

jobs:
  build-and-process:
    # Use a standard Linux runner for speed and compatibility
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.11'] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # 1. Set up the Python environment
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          # Use caching to speed up subsequent dependency installs
          cache: 'pip' 
          
      # 2. Install Dependencies (Uses the OS-compatible makefile)
      - name: Install Dependencies (make install)
        run: make install 
        
      # 3. Execute the AQI Prediction Notebook
      - name: Run AQI Prediction Notebook
        run: make run-aqi-nb
        
      # 4. Execute the Pollen Models Notebook
      - name: Run Pollen Models Notebook
        run: make run-pollen-nb

      # 5. Verify Streamlit App Existence
      - name: Verify Streamlit App Existence
        run: |
          # Use 'test -f' (standard Linux/bash file check)
          if test -f "visualizations/Plum/script/streamlit.py"; then
            echo "Streamlit app file found and ready."
          else
            echo "Streamlit app file NOT found at expected path."
            exit 1
          fi

      # 6. Archive the Executed Notebooks for verification
      - name: Archive Executed Notebooks
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: |
            Models/aqi_model/aqi_predict_cts.ipynb
            Models/pollen_models/pollen_models.ipynb

      # 7. Clean up 
      # - name: Cleanup
      #   run: make clean