name: Python CI with Jupyter & Streamlit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-process:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.11'] 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip' 
          
      # 1. Install Dependencies (USING WORKAROUND to override broken paths)
      # This explicitly tells the Makefile to use the 'bin' path instead of 'Scripts'
      - name: Install Dependencies (make install)
        run: |
          make install \
            PYTHON=./venv/bin/python \
            PIP=./venv/bin/pip \
            JUPYTER=./venv/bin/jupyter
        
      # 2. Execute the AQI Prediction Notebook (Also needs the overrides)
      - name: Run AQI Prediction Notebook
        run: make run-aqI-nb JUPYTER=./venv/bin/jupyter

      # 3. Execute the Pollen Models Notebook (Also needs the overrides)
      - name: Run Pollen Models Notebook
        run: make run-pollen-nb JUPYTER=./venv/bin/jupyter

      # 4. Verify Streamlit App Existence
      - name: Verify Streamlit App Existence
        run: |
          if [ -f "visualizations/Plum/script/streamlit.py" ]; then
            echo "Streamlit app file found and ready."
          else
            echo "Streamlit app file NOT found at expected path."
            exit 1
          fi

      # 5. Archive the Executed Notebooks for verification
      - name: Archive Executed Notebooks
        uses: actions/upload-artifact@v4
        with:
          name: executed-notebooks
          path: |
            Models/aqi_model/aqi_predict_cts.ipynb
            Models/pollen_models/pollen_models.ipynb